queueServer: "queue"
targetServer: "main"
maxPlayers: 100
graceMinutes: 5
gracePriority: 1000

# Formula to calculate player priority in the queue
# Variables available:
# - %lp_priority% : Player's LuckPerms priority (from dreamingqueue:priority meta)
# - %online_time% : Player's online time in seconds (only counts time in target server)
# - %grace_active% : 1 if player is in grace period, 0 otherwise
# 
# Examples:
# - Basic: "%lp_priority%" (just use LuckPerms priority)
# - With time bonus: "%lp_priority% + (%online_time% / 360)" (add ~10 points per hour played)
# - With grace period: "%lp_priority% + (%online_time% / 360) + (%grace_active% * 1000)" (add 1000 if in grace period)
# - Advanced: "(%lp_priority% * 100) + Math.min(500, %online_time% / 72) + (%grace_active% * 800)" (LP priority primary, capped time bonus, grace period bonus)
priorityFormula: "%lp_priority% + (%online_time% / 360) + (%grace_active% * 1000)"
